db5fuse: src/asf.c File Reference
src/asf.c File Reference
Source - Asf file format.
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>
#include <limits.h>
#include "asf.h"
#include "db5_types.h"
#include "file.h"
#include "logger.h"
#include "check.h"
#include "wstring.h"
Classes
struct asf_tag_t
asf tag
Defines
#define ASF_MAGIC 0x3026b275
asf file magic value
#define SIZEOF_TAG 34
size of asf tag
Typedefs
typedef unsigned char guid_t [16]
UID of an asf tag.
typedef struct asf_tag_t asf_tag
asf tag
Functions
bool asf_generate_row (const char *filename, db5_row *row)
generate a db5 row retrieving needed informations in file
Variables
const guid_t title_artist = { 0x33, 0x26, 0xB2, 0x75, 0x8E, 0x66, 0xCF, 0x11, 0xA6, 0xD9, 0x00, 0xAA, 0x00, 0x62, 0xCE, 0x6C }
first UID of asf header
Detailed Description
Source - Asf file format.
Author:
Julien Blitte
Version:
0.1
Definition in file asf.c.
Function Documentation
bool asf_generate_row (const char * filename, db5_row * row)
generate a db5 row retrieving needed informations in file
Parameters:
filename the local filename - utf8
row a pointer to return results
Returns:
true if successfull
Definition at line 106 of file asf.c.
References add_log(), ADDLOG_DEBUG, ADDLOG_DUMP, ADDLOG_NOTICE, ADDLOG_RECOVER, db5_row::album, db5_row::artist, asf_tag_t::artist_size, db5_row::bitrate, check, db5_row::duration, file_common_buffer, file_filesize(), db5_row::filesize, db5_row::genre, membersizeof, asf_tag_t::record_size, db5_row::samplerate, SIZEOF_TAG, db5_row::title, title_artist, asf_tag_t::title_size, ws_wstoa(), and db5_row::year.
Referenced by db5_generate_row().