db5fuse: inc/asf.h File Reference
inc/asf.h File Reference
Source - Header - Asf fi.
#include <stdbool.h>
#include "db5_types.h"
Functions
bool asf_generate_row (const char *filename, db5_row *row)
generate a db5 row retrieving needed informations in file
Detailed Description
Source - Header - Asf fi.
Author:
Julien Blitte
Version:
0.1
Definition in file asf.h.
Function Documentation
bool asf_generate_row (const char * filename, db5_row * row)
generate a db5 row retrieving needed informations in file
Parameters:
filename the local filename - utf8
row a pointer to return results
Returns:
true if successfull
Definition at line 87 of file asf.c.
References add_log(), ADDLOG_NOTICE, ADDLOG_RECOVER, db5_row::album, db5_row::artist, asf_tag_t::artist_size, db5_row::bitrate, check, db5_row::duration, file_common_buffer, file_filesize(), db5_row::filesize, db5_row::genre, log_dump(), membersizeof, asf_tag_t::record_size, db5_row::samplerate, SIZEOF_TAG, db5_row::title, title_artist, asf_tag_t::title_size, ws_wstoa(), and db5_row::year.
Referenced by db5_generate_row().