db5fuse: inc/crc32.h File Reference
inc/crc32.h File Reference
Header - Crc32 checksum.
#include <stdint.h>
#include <stdlib.h>
Defines
#define CRC32_POLYNOMINAL 0x04c11db7
traditional polynomial value
#define crc32_init() crc32_init_seed(CRC32_POLYNOMINAL);
initialize crc32 compute table with default seed
Functions
void crc32_init_seed (const uint32_t polynominal)
initialize crc32 compute table
uint32_t crc32 (const char *data, const size_t size)
compute an array crc32 checksum
uint32_t crc32_file (const char *path)
compute a file crc32 checksum
uint32_t strcrc32 (const char *data)
compute a string crc32 checksum
Detailed Description
Header - Crc32 checksum.
Author:
Julien Blitte
Version:
0.1
Definition in file crc32.h.
Function Documentation
uint32_t crc32 (const char * data, const size_t size) [inline]
compute an array crc32 checksum
Parameters:
data data source
size size of source
Returns:
data checksum
Definition at line 79 of file crc32.c.
Referenced by db5_index_index_column().
uint32_t crc32_file (const char * path)
compute a file crc32 checksum
Parameters:
path file source - utf8
Returns:
file checksum
Definition at line 100 of file crc32.c.
References CRC_BUFFER_SIZE.
void crc32_init_seed (const uint32_t polynominal)
initialize crc32 compute table
Parameters:
polynominal seed
Definition at line 60 of file crc32.c.
uint32_t strcrc32 (const char * data)
compute a string crc32 checksum
Parameters:
data string source
Returns:
string checksum
Definition at line 84 of file crc32.c.
Referenced by names_generate_shortname(), and names_insert().