db5fuse: src/db5_index.c File Reference
src/db5_index.c File Reference
Source - Database db5, index.
#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include "check.h"
#include "db5_dat.h"
#include "db5_hdr.h"
#include "db5_index.h"
#include "db5_types.h"
#include "file.h"
#include "crc32.h"
#include "logger.h"
Classes
struct index_entry
index entry
Defines
#define byteof(c, i) (((char *)&c)[(i)])
get n-th byte of an object
Functions
bool db5_index_index_column (const ptrdiff_t reloffset, const size_t size, const uint32_t code)
index a column (system)
Detailed Description
Source - Database db5, index.
Author:
Julien Blitte
Version:
0.1
Definition in file db5_index.c.
Function Documentation
bool db5_index_index_column (const ptrdiff_t reloffset, const size_t size, const uint32_t code)
index a column (system)
Parameters:
reloffset element address in structure line
size size of element
code index code to generate
Returns:
true if successfull
Definition at line 84 of file db5_index.c.
References add_log(), ADDLOG_DEBUG, ADDLOG_FAIL, ADDLOG_NOTICE, byteof, check, CONFIG_DB5_DATA_DIR, CONFIG_DB5_IDX_FILE, crc32(), db5_dat_select_row(), db5_hdr_count(), file_fcaseopen(), index_entry::hidden, membersizeof, index_entry::position, and index_entry::uid.