db5fuse: inc/db5_dat.h File Reference
inc/db5_dat.h File Reference
Header - Database db5, data.
#include <stdbool.h>
#include <stdint.h>
#include "db5_types.h"
Defines
#define DB5_ROW_NOT_FOUND ((uint32_t)-1)
magic value returned when a row is not found in database
#define db5_dat_str_extract(member) db5_dat_select_string_column(offsetof(db5_row,member),membersizeof(db5_row,member))
extract a string column from database (user friendly)
#define db5_dat_num_extract(member) db5_dat_select_number_column(offsetof(db5_row,member))
extract a number column from database (user friendly)
Functions
bool db5_dat_init ()
initialize databse
void db5_dat_free ()
clean database on exiting
bool db5_dat_select_row (const uint32_t index, db5_row *entry)
read an entry into database
bool db5_dat_update (const uint32_t index, db5_row *entry)
modify an entry into database
bool db5_dat_insert (db5_row *entry)
add an entry into database
bool db5_dat_delete_row (const uint32_t index)
delete an entry of database
uint32_t db5_dat_select_by_filename (const char *filename)
find a row corresponding to a file
db5_string_entry * db5_dat_select_string_column (const size_t reloffset, const size_t size)
extract a string column from database (system)
void db5_dat_free_string_column (db5_string_entry *index, const uint32_t count)
free a string column
db5_number_entry * db5_dat_select_number_column (const size_t reloffset)
extract a number column from database (system)
void db5_dat_free_number_column (db5_number_entry *index)
free a number column
Detailed Description
Header - Database db5, data.
Author:
Julien Blitte
Version:
0.1
Definition in file db5_dat.h.
Define Documentation
#define db5_dat_num_extract (member) db5_dat_select_number_column(offsetof(db5_row,member))
extract a number column from database (user friendly)
Parameters:
member the column to extract
Returns:
corresponding column
Definition at line 101 of file db5_dat.h.
#define db5_dat_str_extract (member) db5_dat_select_string_column(offsetof(db5_row,member),membersizeof(db5_row,member))
extract a string column from database (user friendly)
Parameters:
member the column to extract
Returns:
corresponding column
Definition at line 80 of file db5_dat.h.
Function Documentation
bool db5_dat_delete_row (const uint32_t index)
delete an entry of database
Parameters:
index entry position
Returns:
true if is successfull
Definition at line 117 of file db5_dat.c.
References add_log(), ADDLOG_FAIL, db5_dat_select_row(), db5_dat_update(), db5_hdr_count(), db5_hdr_grow(), and file_truncate().
Referenced by db5_delete().
void db5_dat_free_number_column (db5_number_entry * index) [inline]
free a number column
Parameters:
index the number column to free
Definition at line 284 of file db5_dat.c.
References check.
Referenced by db5_idx_index_number_column().
void db5_dat_free_string_column (db5_string_entry * index, const uint32_t count)
free a string column
Parameters:
index the string column to free
count number of lines
Definition at line 239 of file db5_dat.c.
References check.
Referenced by db5_dat_select_string_column(), and db5_idx_index_string_column().
bool db5_dat_init ()
initialize databse
Returns:
true if is successfull
Definition at line 30 of file db5_dat.c.
References add_log(), ADDLOG_CRITICAL, CONFIG_DB5_DAT_FILE, CONFIG_DB5_DATA_DIR, crc32_init, and file_fcaseopen().
Referenced by db5_init().
bool db5_dat_insert (db5_row * entry)
add an entry into database
Parameters:
entry new entry
Returns:
true if is successfull
Definition at line 86 of file db5_dat.c.
References add_log(), ADDLOG_FAIL, check, CONFIG_MAX_DB5_ENTRY, db5_hdr_count(), and db5_hdr_grow().
Referenced by db5_insert().
uint32_t db5_dat_select_by_filename (const char * filename)
find a row corresponding to a file
Parameters:
filename the local filename - latin1
Returns:
row position, (unsigned)-1 if no found
Definition at line 163 of file db5_dat.c.
References add_log(), ADDLOG_FAIL, check, db5_dat_select_row(), db5_hdr_count(), DB5_ROW_NOT_FOUND, db5_row::filename, filename_size, and ws_atows().
Referenced by db5_delete(), db5_insert(), db5_longname_to_shortname(), and db5_update().
db5_number_entry* db5_dat_select_number_column (const size_t reloffset)
extract a number column from database (system)
Parameters:
reloffset structure offset
Returns:
corresponding column
Definition at line 254 of file db5_dat.c.
References check, db5_dat_select_row(), db5_hdr_count(), db5_number_entry::position, and db5_number_entry::value.
Referenced by db5_idx_index_number_column().
bool db5_dat_select_row (const uint32_t index, db5_row * entry)
read an entry into database
Parameters:
index entry position
entry read entry
Returns:
true if is successfull
Definition at line 50 of file db5_dat.c.
References add_log(), ADDLOG_FAIL, and check.
Referenced by db5_dat_delete_row(), db5_dat_select_by_filename(), db5_dat_select_number_column(), db5_dat_select_string_column(), and db5_select_filename().
db5_string_entry* db5_dat_select_string_column (const size_t reloffset, const size_t size)
extract a string column from database (system)
Parameters:
reloffset structure offset
size value size
Returns:
corresponding column
Definition at line 192 of file db5_dat.c.
References add_log(), ADDLOG_FAIL, check, db5_string_entry::crc32, db5_dat_free_string_column(), db5_dat_select_row(), db5_hdr_count(), db5_string_entry::position, strcrc32(), db5_string_entry::value, and ws_wstoa().
Referenced by db5_idx_index_string_column().
bool db5_dat_update (const uint32_t index, db5_row * entry)
modify an entry into database
Parameters:
index entry position
entry new entry
Returns:
true if is successfull
Definition at line 68 of file db5_dat.c.
References add_log(), ADDLOG_FAIL, and check.
Referenced by db5_dat_delete_row(), and db5_update().