db5fuse: src/db5_idx.c File Reference
src/db5_idx.c File Reference
Source - Database db5, index.
#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include "check.h"
#include "db5_dat.h"
#include "db5_hdr.h"
#include "db5_idx.h"
#include "db5_types.h"
#include "file.h"
#include "logger.h"
Defines
#define byteof(c, i) (((char *)&c)[(i)])
get n-th byte of an object
Functions
void db5_idx_order_number_column (db5_number_entry *list, const uint32_t count)
order a number column
bool db5_idx_index_column_full (void *index, const uint32_t count, const uint32_t code, const bool numeric)
generate an index
bool db5_idx_index_string_column (const size_t reloffset, const size_t size, const uint32_t code)
index a string column (system)
bool db5_idx_index_number_column (const size_t reloffset, const uint32_t code)
index a number column (system)
Detailed Description
Source - Database db5, index.
Author:
Julien Blitte
Version:
0.1
Definition in file db5_idx.c.
Function Documentation
bool db5_idx_index_column_full (void * index, const uint32_t count, const uint32_t code, const bool numeric)
generate an index
Parameters:
index data pointer
count number of elements
code index code to generate
numeric true is data are number
Returns:
true if successfull
Definition at line 88 of file db5_idx.c.
References byteof, check, CONFIG_DB5_DATA_DIR, CONFIG_DB5_IDX_FILE, and file_fcaseopen().
Referenced by db5_idx_index_number_column(), and db5_idx_index_string_column().
bool db5_idx_index_number_column (const size_t reloffset, const uint32_t code)
index a number column (system)
Parameters:
reloffset element address in structure line
code index code to generate
Returns:
true if successfull
Definition at line 162 of file db5_idx.c.
References add_log(), ADDLOG_FAIL, byteof, check, db5_dat_free_number_column(), db5_dat_select_number_column(), db5_hdr_count(), db5_idx_index_column_full(), and db5_idx_order_number_column().
bool db5_idx_index_string_column (const size_t reloffset, const size_t size, const uint32_t code)
index a string column (system)
Parameters:
reloffset element address in structure line
size size of element
code index code to generate
Returns:
true if successfull
Definition at line 132 of file db5_idx.c.
References add_log(), ADDLOG_FAIL, byteof, check, db5_dat_free_string_column(), db5_dat_select_string_column(), db5_hdr_count(), and db5_idx_index_column_full().
void db5_idx_order_number_column (db5_number_entry * list, const uint32_t count)
order a number column
Parameters:
list number column
count number of entries
Definition at line 73 of file db5_idx.c.
References check.
Referenced by db5_idx_index_number_column().