db5fuse: inc/db5_idx.h File Reference
inc/db5_idx.h File Reference
Header - Database db5, index.
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <stdint.h>
#include "db5_types.h"
#include "db5_dat.h"
Defines
#define DB5_IDX_CODE_DEV 0x56454440
index used for test - ascii - not null terminated
#define DB5_IDX_CODE_FILENAME 0x4d414e46
filename index - ascii - not null terminated
#define DB5_IDX_CODE_FILEPATH 0x48545046
filepath index - ascii - not null terminated
#define DB5_IDX_CODE_ALBUM 0x424c4154
album index - ascii - not null terminated
#define DB5_IDX_CODE_GENRE 0x4e4f4354
genre index - ascii - not null terminated
#define DB5_IDX_CODE_TITLE 0x32544954
title index - ascii - not null terminated
#define DB5_IDX_CODE_ARTIST 0x31455054
artist index - ascii - not null terminated
#define DB5_IDX_CODE_TRACK 0x4b435254
track index - ascii - not null terminated
#define DB5_IDX_CODE_SOURCE 0x43525358
source index - ascii - not null terminated
#define db5_idx_index_str(member, code) db5_idx_index_string_column(offsetof(db5_row,member),membersizeof(db5_row,member),code)
index a string column (user friendly)
#define db5_idx_index_num(member, code) db5_idx_index_number_column(offsetof(db5_row,member),code)
index a numeric column (user friendly)
Functions
bool db5_idx_index_string_column (const size_t reloffset, const size_t size, const uint32_t code)
index a string column (system)
bool db5_idx_index_number_column (const size_t reloffset, const uint32_t code)
index a number column (system)
Detailed Description
Header - Database db5, index.
Author:
Julien Blitte
Version:
0.1
Definition in file db5_idx.h.
Define Documentation
#define db5_idx_index_num (member, code) db5_idx_index_number_column(offsetof(db5_row,member),code)
index a numeric column (user friendly)
Parameters:
member element in structure line
code index code to generate
Returns:
true if successfull
Definition at line 69 of file db5_idx.h.
Referenced by db5_index().
#define db5_idx_index_str (member, code) db5_idx_index_string_column(offsetof(db5_row,member),membersizeof(db5_row,member),code)
index a string column (user friendly)
Parameters:
member element in structure line
code index code to generate
Returns:
true if successfull
Definition at line 53 of file db5_idx.h.
Referenced by db5_index().
Function Documentation
bool db5_idx_index_number_column (const size_t reloffset, const uint32_t code)
index a number column (system)
Parameters:
reloffset element address in structure line
code index code to generate
Returns:
true if successfull
Definition at line 162 of file db5_idx.c.
References add_log(), ADDLOG_FAIL, byteof, check, db5_dat_free_number_column(), db5_dat_select_number_column(), db5_hdr_count(), db5_idx_index_column_full(), and db5_idx_order_number_column().
bool db5_idx_index_string_column (const size_t reloffset, const size_t size, const uint32_t code)
index a string column (system)
Parameters:
reloffset element address in structure line
size size of element
code index code to generate
Returns:
true if successfull
Definition at line 132 of file db5_idx.c.
References add_log(), ADDLOG_FAIL, byteof, check, db5_dat_free_string_column(), db5_dat_select_string_column(), db5_hdr_count(), and db5_idx_index_column_full().