db5fuse: src/logger.c File Reference
src/logger.c File Reference
Source - Log activities.
#include <assert.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include "logger.h"
#include "utf8.h"
Functions
void open_log ()
initialize log file
bool log_dump_latin1 (const char *var, const char *value)
dump a (latin1) string variable to log
bool log_dump (const char *var, const char *value)
dump a (utf8) string variable to log
bool add_log (int level, const char *context, const char *format,...)
add an entry to log file
void close_log ()
close log file
Detailed Description
Source - Log activities.
Author:
Julien Blitte
Version:
0.1
Definition in file logger.c.
Function Documentation
bool add_log (int level, const char * context, const char * format, ...)
add an entry to log file
Parameters:
level log level
context of event (object, library, etc.) - utf8
format text to log (printf format) - utf8
Returns:
true if successfull
Definition at line 57 of file logger.c.
References CONFIG_LOG_FILENAME, CONFIG_LOG_LEVEL, LOG_DEBUG, and LOG_EMERG.
Referenced by asf_generate_row(), db5_dat_delete_row(), db5_dat_init(), db5_dat_insert(), db5_dat_select_by_filename(), db5_dat_select_row(), db5_dat_update(), db5_delete(), db5_exists(), db5_generate_row(), db5_hdr_count(), db5_hdr_grow(), db5_hdr_init(), db5_index(), db5_index_index_column(), db5_insert(), db5_localfile(), db5_longname_to_shortname(), db5_print_row(), db5_select_filename(), db5_shortname_to_localfile(), db5_update(), file_fcaseopen(), file_filesize(), file_filesize_f(), file_set_context(), file_truncate(), fuse_impl_create(), fuse_impl_destroy(), fuse_impl_flush(), fuse_impl_fsync(), fuse_impl_getattr(), fuse_impl_init(), fuse_impl_open(), fuse_impl_read(), fuse_impl_readdir(), fuse_impl_rename(), fuse_impl_statfs(), fuse_impl_truncate(), fuse_impl_unlink(), fuse_impl_utimens(), fuse_impl_write(), log_dump(), log_dump_latin1(), mp3_generate_row(), names_delete(), names_init(), names_insert(), names_print(), names_save(), and names_select_shortname().
bool log_dump (const char * var, const char * value)
dump a (utf8) string variable to log
Parameters:
var name of variable - utf8
value variable content - utf8
Returns:
true if successfull
Definition at line 49 of file logger.c.
References add_log(), and ADDLOG_DUMP.
Referenced by db5_delete(), db5_generate_row(), db5_insert(), db5_longname_to_shortname(), db5_shortname_to_localfile(), db5_update(), file_fcaseopen(), file_filesize(), file_set_context(), fuse_impl_create(), fuse_impl_getattr(), fuse_impl_rename(), fuse_impl_truncate(), fuse_impl_unlink(), and fuse_impl_utimens().
bool log_dump_latin1 (const char * var, const char * value)
dump a (latin1) string variable to log
Parameters:
var name of variable - utf8
value variable content - latin1
Returns:
true if successfull
Definition at line 37 of file logger.c.
References add_log(), ADDLOG_DUMP, and iso8859_utf8().
Referenced by db5_delete(), db5_generate_row(), db5_insert(), db5_longname_to_shortname(), db5_print_row(), db5_shortname_to_localfile(), db5_update(), names_insert(), names_print(), and names_select_shortname().