db5fuse: src/mp3_id3.c File Reference
src/mp3_id3.c File Reference
Source - Mp3 file format, id3 tags.
#include <id3tag.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "check.h"
#include "mp3_id3.h"
#include "wstring.h"
Functions
id3_latin1_t const * id3_field_getlatin1s (union id3_field const *field, unsigned int index)
id3tag lack: get a latin1 string list item
id3_latin1_t * id3_latin1duplicate (id3_latin1_t const *source)
duplicate an id3_latin1_t string
char * id3_get_string (struct id3_tag *tag, char const *frameid)
get a id3 tag value (string)
unsigned long id3_get_int (struct id3_tag *tag, char const *frameid)
get a id3 tag value (string)
Variables
const char * id3_genres []
standard id3 genres
Detailed Description
Source - Mp3 file format, id3 tags.
Author:
Julien Blitte
Version:
0.1
Definition in file mp3_id3.c.
Function Documentation
id3_latin1_t const* id3_field_getlatin1s (union id3_field const * field, unsigned int index)
id3tag lack: get a latin1 string list item
Parameters:
field id3 field
index string index
Returns:
string to extract
Definition at line 23 of file mp3_id3.c.
Referenced by id3_get_string().
unsigned long id3_get_int (struct id3_tag * tag, char const * frameid)
get a id3 tag value (string)
Parameters:
tag pointer to tag structure
frameid the value to get - ascii
Returns:
tag value
Definition at line 134 of file mp3_id3.c.
References check, id3_get_string(), and ID3_INT_ERROR.
char* id3_get_string (struct id3_tag * tag, char const * frameid)
get a id3 tag value (string)
Parameters:
tag pointer to tag structure
frameid the value to get - ascii
Returns:
tag value
Definition at line 71 of file mp3_id3.c.
References check, id3_field_getlatin1s(), id3_latin1duplicate(), and ID3_STRING_ERROR.
Referenced by id3_get_int().
id3_latin1_t* id3_latin1duplicate (id3_latin1_t const * source)
duplicate an id3_latin1_t string
Parameters:
source string to duplicate
Returns:
a copy of source (do not forget to free it)
Definition at line 34 of file mp3_id3.c.
References check.
Referenced by id3_get_string().
Variable Documentation
const char* id3_genres[]
Initial value:
 { "Blues", "Classic Rock", "Country", "Dance", "Disco", "Funk", "Grunge", "Hip-Hop",
                        "Jazz", "Metal", "New Age", "Oldies", "Other", "Pop", "R&B", "Rap",
                        "Reggae", "Rock", "Techno", "Industrial", "Alternative", "Ska", "Death Metal", "Pranks",
                        "Soundtrack", "Euro-Techno", "Ambient", "Trip-Hop", "Vocal", "Jazz+Funk", "Fusion", "Trance",
                        "Classical", "Instrumental", "Acid", "House", "Game", "Sound Clip", "Gospel", "Noise",
                        "AlternRock", "Bass", "Soul", "Punk", "Space", "Meditative", "Instrumental Pop", "Instrumental Rock",
                        "Ethnic", "Gothic", "Darkwave", "Techno-Industrial", "Electronic", "Pop-Folk", "Eurodance", "Dream",
                        "Southern Rock", "Comedy", "Cult", "Gangsta", "Top 40", "Christian Rap", "Pop/Funk", "Jungle",
                        "Native American", "Cabaret", "New Wave", "Psychadelic", "Rave", "Showtunes", "Trailer", "Lo-Fi",
                        "Tribal", "Acid Punk", "Acid Jazz", "Polka", "Retro", "Musical", "Rock & Roll", "Hard Rock",
                        "Folk", "Folk-Rock", "National Folk", "Swing", "Fast Fusion", "Bebob", "Latin", "Revival",
                        "Celtic", "Bluegrass", "Avantgarde", "Gothic Rock", "Progressive Rock", "Psychedelic Rock", "Symphonic Rock", "Slow Rock",
                        "Big Band", "Chorus", "Easy Listening", "Acoustic", "Humour", "Speech", "Chanson", "Opera",
                        "Chamber Music", "Sonata", "Symphony", "Booty Bass", "Primus", "Porn Groove", "Satire", "Slow Jam",
                        "Club", "Tango", "Samba", "Folklore", "Ballad", "Power Ballad", "Rhythmic Soul", "Freestyle",
                        "Duet", "Punk Rock", "Drum Solo", "A capella", "Euro-House", "Dance Hall" }
standard id3 genres
music genres defined
Definition at line 54 of file mp3_id3.c.