db5fuse: inc/mp3_id3.h File Reference
inc/mp3_id3.h File Reference
Header - Mp3 file format, id3 tags.
Defines
#define ID3_STRING_ERROR (NULL)
magic value returned when an error occurs (string)
#define ID3_INT_ERROR ((unsigned)-1)
magic value returned when an error occurs (integer)
#define ID3_NB_GENRES 127
number of music genres
Functions
char * id3_get_string (struct id3_tag *tag, char const *frameid)
get a id3 tag value (string)
unsigned long id3_get_int (struct id3_tag *tag, char const *frameid)
get a id3 tag value (string)
Variables
const char * id3_genres [ID3_NB_GENRES]
music genres defined
Detailed Description
Header - Mp3 file format, id3 tags.
Author:
Julien Blitte
Version:
0.1
Definition in file mp3_id3.h.
Function Documentation
unsigned long id3_get_int (struct id3_tag * tag, char const * frameid)
get a id3 tag value (string)
Parameters:
tag pointer to tag structure
frameid the value to get - ascii
Returns:
tag value
Definition at line 134 of file mp3_id3.c.
References check, id3_get_string(), and ID3_INT_ERROR.
char* id3_get_string (struct id3_tag * tag, char const * frameid)
get a id3 tag value (string)
Parameters:
tag pointer to tag structure
frameid the value to get - ascii
Returns:
tag value
Definition at line 71 of file mp3_id3.c.
References check, id3_field_getlatin1s(), id3_latin1duplicate(), and ID3_STRING_ERROR.
Referenced by id3_get_int().