db5fuse: inc/utf8.h File Reference
inc/utf8.h File Reference
Header - Unicode utf-8.
Functions
size_t iso8859_utf8 (const char *source, char *dest, const size_t dest_size)
convert iso to unicode
size_t utf8_iso8859 (const char *source, char *dest, const size_t dest_size)
convert iso to unicode
Detailed Description
Header - Unicode utf-8.
Author:
Julien Blitte
Version:
0.1
Definition in file utf8.h.
Function Documentation
size_t iso8859_utf8 (const char * source, char * dest, const size_t dest_size)
convert iso to unicode
Parameters:
source latin1 string to convert to utf8 - latin1
dest destination where new string is stored - utf8
dest_size size of dest
Returns:
size of new string
Definition at line 58 of file utf8.c.
References check, UTF8_HEADER_11, UTF8_HEADER_7, UTF8_SHIFTER, and UTF8_TAILER.
Referenced by db5_select_filename(), db5_shortname_to_localfile(), and log_dump_latin1().
size_t utf8_iso8859 (const char * source, char * dest, const size_t dest_size)
convert iso to unicode
Parameters:
source utf8 string to convert to latin1 - utf8
dest destination where new string is stored - latin1
dest_size size of dest
Returns:
size of new string
Definition at line 95 of file utf8.c.
References check, IS_UTF8_HEADER_11, IS_UTF8_HEADER_7, UTF8_UNHEADER_11, UTF8_UNHEADER_7, UTF8_UNSHIFTER, and UTF8_UNTAILER.
Referenced by db5_generate_row(), db5_insert(), and db5_longname_to_shortname().