db5fuse: src/wstring.c File Reference
src/wstring.c File Reference
Source - Widechar string.
#include <stdlib.h>
#include "check.h"
#include <string.h>
#include "wstring.h"
Functions
void ws_wstoa (char *widestring, const size_t length)
convert a widechar string to char string
void ws_atows (char *string, const size_t length)
convert a char string to widechar string
void * ws_memswapcpy (void *dest, void *src, const size_t len)
copy memory area reversing byte order
Detailed Description
Source - Widechar string.
Author:
Julien Blitte
Version:
0.1
Definition in file wstring.c.
Function Documentation
void ws_atows (char * string, const size_t length)
convert a char string to widechar string
Parameters:
string char string to turn to widechar string, this parameter is altered - latin1
length of string
Definition at line 27 of file wstring.c.
References check.
Referenced by db5_dat_select_by_filename(), and db5_widechar_row().
void* ws_memswapcpy (void * dest, void * src, const size_t len)
copy memory area reversing byte order
Parameters:
dest destination - binary
src source - binary
len size of data
Definition at line 40 of file wstring.c.
References check.
void ws_wstoa (char * widestring, const size_t length)
convert a widechar string to char string
Parameters:
widestring string to turn to char string, this parameter is altered - widechar latin1
length of widestring
Definition at line 12 of file wstring.c.
References check.
Referenced by asf_generate_row(), and db5_unwidechar_row().